In [168]:
import numpy as np
from numpy import linalg as LA
from sklearn import metrics

# Implementing Pereceptron model

***

In [169]:
#####Single Neuron Perceptron#####
##################################

In [189]:
X=np.array([[2.7, -2.5], [-1.4, 2.3], [3.3, -4.4], [-1.3,1.8]])
X

array([[2.700, -2.500],
       [-1.400, 2.300],
       [3.300, -4.400],
       [-1.300, 1.800]])

In [171]:
def step_binary(v):
    return 1 * (v > 0)

In [172]:
def perceptron(x, w, b):
    in_ = np.dot(x,w) + b
    output = step_binary(in_)
    return output

In [190]:
#initialise the weights and the bias 
weights = np.array([-0.2, 0.7])
b = 0

#calculating output for a single instance (i.e. the input to the perceptron is a single vector)
for i in range(X.shape[0]):
    print("input: ", X[i], ", output: ", perceptron(X[i],weights, b))

input:  [2.700 -2.500] , output:  0
input:  [-1.400 2.300] , output:  1
input:  [3.300 -4.400] , output:  0
input:  [-1.300 1.800] , output:  1


In [174]:
#calculating output for a set of instances (i.e. the input to the perceptron is a matrix)
predictions = perceptron(X,weights,b)
print(predictions)

[0 1 0 1]


---------------Using bigger dataset for classification-----------------

In [191]:
#Read data from a text file
from sklearn import preprocessing
data = np.loadtxt("diabetes_binary_classification.txt")

# split into inputs and outputs
X, y = data[:, :-1], data[:, -1]

#scaling the input data
X = preprocessing.MinMaxScaler().fit_transform(X)

print ("X.shape:", X.shape)
print ("y.shape:", y.shape)
np.count_nonzero(y)

X.shape: (768, 8)
y.shape: (768,)


268

In [194]:
#Initialising parameters from a uniform distribution over [-1, 1) 
np.random.seed(0)
weights = np.random.uniform(-1,1,X.shape[1])
b = np.random.uniform(-1,1,1)
#Passing instances through the network
predictions = perceptron(X,weights, b)

#Evaluating the performance
print('MSE: ', metrics.mean_squared_error(predictions,y))
print('Accuracy:', metrics.accuracy_score(predictions,y))
print('F1:', metrics.f1_score(predictions,y))

MSE:  0.6510416666666666
Accuracy: 0.3489583333333333
F1: 0.5173745173745173


# Perceptron Training

------------------------------------


In [198]:
def updateRule(X,y,lr):
    np.random.seed(0)
    weights = np.random.uniform(-1,1,X.shape[1])
    b = np.random.uniform(-1,1,1)
    
    for k in range(100):
        for i in range(len(X)):
            prediction = perceptron(X[i], weights, b)
            error = y[i]-prediction
            weights = weights + lr * error * X[i]
            b = b + lr*error
    
    #Calculating predictions
    predictions = perceptron(X,weights, b)
    #Calculating error
    print('MSE: ', metrics.mean_squared_error(predictions,y))
    print('Accuracy:', metrics.accuracy_score(predictions,y))
    print('F1:', metrics.f1_score(predictions,y))

In [199]:
updateRule(X,y,0.05) 

MSE:  0.24088541666666666
Accuracy: 0.7591145833333334
F1: 0.673721340388007


# Multilayer Perceptron

***

In [185]:
#passing a single training instance through the network
def feedforward(x):
    #initialise weights
    np.random.seed(0)
    w_ih = np.random.uniform(-1,1,[X.shape[1],2])
    w_ho = np.random.uniform(-1,1,[2,1])

    #initialise bias
    b_ih = np.random.uniform(-1,1,[1,2])
    b_ho = np.random.uniform(-1,1,1)
    
    #calculating input to the hidden layer
    in_h = x@w_ih + b_ih
    
    #calculating output of the hidden layer
    out_h = step_binary(in_h)
    
    #calculating input to the output layer
    in_o = out_h@w_ho + b_ho
    
    #calculating output of the output layer
    out_o = step_binary(in_o)

    return out_o

In [186]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
for i in range(5):
    print('Input: ', X[i], 'Output: ', feedforward(X[i]))

Input:  [0.353 0.744 0.590 0.354 0.000 0.501 0.234 0.483] Output:  [[1]]
Input:  [0.059 0.427 0.541 0.293 0.000 0.396 0.117 0.167] Output:  [[1]]
Input:  [0.471 0.920 0.525 0.000 0.000 0.347 0.254 0.183] Output:  [[1]]
Input:  [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.000] Output:  [[1]]
Input:  [0.000 0.688 0.328 0.354 0.199 0.642 0.944 0.200] Output:  [[1]]


In [200]:
#passing entire train data through the network
def feedforward_(X):
    #initialise weights
    np.random.seed(0)
    w_ih = np.random.uniform(-1,1,[X.shape[1],2])
    w_ho = np.random.uniform(-1,1,[2,1])

    #initialise bias
    b_ih = np.random.uniform(-1,1,[1,2])
    b_ho = np.random.uniform(-1,1,1)
    
    #calculating input to the hidden layer
    in_h = X@w_ih + b_ih
    print('in_h: ',in_h.shape)
    
    #calculating output of the hidden layer
    out_h = step_binary(in_h)
    print('out_h: ', out_h.shape)
    
    #calculating input to the output layer
    in_o = out_h@w_ho + b_ho
    print('in_o: ', in_o.shape)
    
    #calculating output of the output layer
    out_o = step_binary(in_o)
    print('out_o: ', out_o.shape)

    return out_o

In [201]:
predictions = feedforward_(X)
print('MSE: ', metrics.mean_squared_error(predictions,y))
print('Accuracy:', metrics.accuracy_score(predictions,y))
print('F1:', metrics.f1_score(predictions,y))

in_h:  (768, 2)
out_h:  (768, 2)
in_o:  (768, 1)
out_o:  (768, 1)
MSE:  0.6510416666666666
Accuracy: 0.3489583333333333
F1: 0.5173745173745173


In [202]:
m = np.array([[1,2,3],[4,5,6]])


In [203]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
v=np.array([1,1,1])

In [131]:
m+v

array([[2, 3, 4],
       [5, 6, 7]])